### ISSUE TITLE
Computation of the likelihood

### ISSUE THREAD

**Issue by maelp** [api-ai/asr-server#13]
Could you explain how you get parameters for the equation <https://github.com/api-ai/asr-server/blob/master/src/OnlineDecoder.cc#L90> and how we can set them for our own models?

**Comment by realill** [comment]
Good find :)
I assume that was done using test corpus where correct result would be 1.0 and incorrect results would be 1.0 - (number of incorrect words)/(total number of words). Then this parameters would be picked by hand or with help of math.

You can try do the same.

This is very unreliable number tho. So my advice - just ignore this.

@folomeev

**Comment by folomeev** [comment]
Yes, it's a kind of magic. It was assumed that likelihood value is a linear combination of lattice weights per word. 

So after model training was complete we used train corpus to select weights factors in order to maximize likelihood of correctly recognized samples and minimize it for incorrect ones.

Actually this is not a really good practice and calculated values become model specific but this approach provides some likelihood estimation in a fast and simple way.
